name: template-optparse
version: '0.0.0.0'
copyright: ! 'Copyright: (c) 2020-2022 Tom Sydney Kerckhove'
license: AllRightsReserved
  
dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - envparse
  - optparse-applicative
  - path
  - path-io
  - text
  - yaml
  - autodocodec
  - autodocodec-yaml

tests:
  template-optparse-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - envparse
    - hspec
    - optparse-applicative
    - template-optparse
    - yaml
